name:  Deploy site

on:
  push:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Checkout cobalt
      uses: actions/checkout@master
      with:
        repository: cobalt-org/cobalt.rs
        path: cobaltrs
        
    - name: Build cobalt
      working-directory: ./cobaltrs
      run: cargo build --release
      
    - name: Build site
      run: ./cobaltrs/target/release/cobalt build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: master
        FOLDER: _build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
