name:  Deploy site

on:
  push:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cobalt
      run: curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs--crate cobalt --force --target x86_64-unknown-linux-gnu --tag v0.15.1
      
    - name: Build site
      run: cobalt build
      
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: master
        FOLDER: _build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
