name: Deploy site

on:
  push:
    branches: [ "bespoke-static-site-generator" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Build bssg
      working-directory: ./tools/bssg
      run: cargo build --release

    - name: Build site
      working-directory: ./tools/bssg
      run: ./tools/bssg/target/release/bssg

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: bespoke-static-site-generator-deployment
        FOLDER: ./workdir/www_out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
